attempt to implement endpoint
alexeyyS000/metropoliten pull request #8
Opened 2023-07-21 22:32 UTC by alexeyyS000

2023-07-22 06:44 UTC, swimmwatch requested changes

2023-07-22 06:44 UTC, swimmwatch commented on app/api.py
> +@app.get("/posts/get/get_one_post/{post_id}")
В пути endpoint-а не должно быть слов глаголов. За "действие" отвечает HTTP метод, который ты выбрал. Например, 
- GET - это получение записи/записей,
- POST - создание записи,
- DELETE - удаление записи
- PUT/PATCH - обновление/модификация записи
- и т. д

Поэтому тут достаточно вполне использовать путь: `/posts/{post_id}`.
По HTTP методу GET и по параметру пути понятно, что тут идет получение записи по ID поста.

2023-07-22 06:44 UTC, swimmwatch commented on app/api.py
> +    return post_repo.get_one_or_none(id=post_id)
В случае, если запись не найдена, у тебя вернется None (предполагаю пустое тело ответа) с HTTP статусом 200. Это некорректный ответ. В данном случае нужно отвечать со статусом [404](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) и в теле ответа указывать текст ошибки: [вот пример как это делается в FastAPI](https://fastapi.tiangolo.com/tutorial/handling-errors/#import-httpexception)

2023-07-22 06:44 UTC, swimmwatch commented on app/api.py
> +async def get_one_post(post_id: int):
Для серилизации/десерилизации нужно указывать и использовать Pydantic схемы. Посмотри этот момент в воркшопе, который я скидывал.

2023-08-03 06:58 UTC, swimmwatch commented on app/api/schemas.py
> +    image_url: Optional[str]
Опционально: есть более простой синтаксис для указания типа, который может принимать `None`: `str | None`
Это тоже самое, что и` Union[str, None]` и `Optional[str]`.

2023-08-03 07:41 UTC, swimmwatch requested changes

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +@router.get("/get_one/{post_id}", response_model=PostDetail)
То же замечание по путям: https://github.com/alexeyyS000/metropoliten/pull/8#discussion_r1271257566
Поправь пожалуйста.

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +@router.post("/create_one/", response_model=PostDetail)
То же замечание по путям: https://github.com/alexeyyS000/metropoliten/pull/8#discussion_r1271257566
Поправь пожалуйста.

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +@router.put("/put_one/{post_id}", response_model=PostDetail)
То же замечание по путям: https://github.com/alexeyyS000/metropoliten/pull/8#discussion_r1271257566
Поправь пожалуйста.

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +@router.patch("/patch_one/{post_id}", response_model=PostDetail)
То же замечание по путям: https://github.com/alexeyyS000/metropoliten/pull/8#discussion_r1271257566
Поправь пожалуйста.

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +@router.delete("/delete_one/", response_model=PostDetail)
То же замечание по путям: https://github.com/alexeyyS000/metropoliten/pull/8#discussion_r1271257566
Поправь пожалуйста.

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +@router.delete("/delete_one/", response_model=PostDetail)
Забыл указать параметр пути.

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +    return deleted_post
При удалении не возвращают деталку. Обычно возвращают пустое тело запроса со [HTTP статусом 204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +    dictrem = {keys: values for keys, values in criteria_dict.items() if values is not None}
Что если нужно будет фильтровать по полю со значением `None` (`null` в JSON)? Думаю, этот варинат нужно проработать.

Например, пользователь захочет фильтровать по полю `image_url = None` (поиск постов, у которых нет картинок).

2023-08-03 07:41 UTC, swimmwatch commented on app/api/api.py
> +    return PostDAL(session_maker).fetch2(limit, page, **dictrem)
Когда пользователь использует пагинацию, ему необходимо знать, сколько всего страниц. Добавь пожалуйста в тело ответа данную информацию.

Также пожалуйста добавь поля, которые будут сообщать, какая предыдущая страница (номер), какая следующая (номер).

Тело ответа будет выглядеть примерно так (если запросить 2-ую страницу):
```json
{"count": 100, "prev": 1, "next": 3, "result": [{}, {}, {}]}
```

2023-08-03 07:41 UTC, swimmwatch commented on app/utils/sql/dal.py
> +    def fetch2(self, limit, page=0, **kwargs):
Номерация страниц начинается с 1. Как в книгах.

2023-08-03 07:41 UTC, swimmwatch commented on app/utils/sql/dal.py
> +            stmt = select(self.Config.model).filter_by(**kwargs).offset(page * limit).limit(limit)
Что если пользователь передаст отрицательные числа? Нужно учесть данный случай. Лучше это сделать в двух местах: на уровне [обработчика FastAPI](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/) (так как он автоматически тебе сделает [ответ со статусом 400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)) и внутри данного метода (выбрасывать исключение `ValueError`).

2023-08-03 16:34 UTC, alexeyyS000 commented on app/api/api.py
> +@router.get("/get_one/{post_id}", response_model=PostDetail)
сделал

2023-08-03 16:34 UTC, alexeyyS000 commented on app/api/api.py
> +@router.post("/create_one/", response_model=PostDetail)
сделал

2023-08-03 16:34 UTC, alexeyyS000 commented on app/api/api.py
> +@router.put("/put_one/{post_id}", response_model=PostDetail)
сделал

2023-08-03 16:34 UTC, alexeyyS000 commented on app/api/api.py
> +@router.patch("/patch_one/{post_id}", response_model=PostDetail)
сделал

2023-08-03 16:35 UTC, alexeyyS000 commented on app/api/api.py
> +    return deleted_post
сделал

2023-08-03 16:35 UTC, alexeyyS000 commented on app/utils/sql/dal.py
> +    def fetch2(self, limit, page=0, **kwargs):
сделал

2023-08-03 16:35 UTC, alexeyyS000 commented on app/utils/sql/dal.py
> +            stmt = select(self.Config.model).filter_by(**kwargs).offset(page * limit).limit(limit)
сделал

2023-08-03 16:43 UTC, swimmwatch requested changes

2023-08-03 16:43 UTC, swimmwatch commented on app/utils/sql/dal.py
> +            total_pages = len(session.execute(select(self.Config.model).filter_by(**kwargs)).scalars().all()) / limit
Данный момент можно сделать одним запросом на уровне SQL: `select count(*) / :limit as total_pages from ...`

В данном случае у тебя тратяться ресурсы на то, чтобы выгрузить в ОЗУ все записи из таблицы, преобразовать их в Python объекты, и только в конце у тебя производиться расчет `total_pages`.  Если записей будет тысячи, то это сильно ударит по производительности. Все вычисления лучше делать на уровне БД через SQL запросы.

2023-08-03 16:43 UTC, swimmwatch commented on app/utils/sql/dal.py
> +            raise ValueError
Когда бросаешь исключение, то нужно писать какой-нибудь сообщение для пользователя, чтобы было понятно в чем заключается исключительная ситуация.

Также рекомендую разделить на два `if`, так как у тебя будет 2 разных по смыслу ошибки.

2023-08-03 16:47 UTC, swimmwatch requested changes

2023-08-03 16:47 UTC, swimmwatch commented on app/utils/sql/dal.py
> +            total_pages = len(session.execute(select(self.Config.model).filter_by(**kwargs)).scalars().all()) / limit
У тебя повторяется запрос: `select(self.Config.model).filter_by(**kwargs)` в двух местах. Лучше вынести это в отдельную переменную.

2023-08-03 16:49 UTC, swimmwatch requested changes

2023-08-06 11:49 UTC, alexeyyS000 commented on app/api/api.py
> +    dictrem = {keys: values for keys, values in criteria_dict.items() if values is not None}
не понимаю пока как это сделать

2023-08-06 11:49 UTC, alexeyyS000 commented on app/api/api.py
> +    return PostDAL(session_maker).fetch2(limit, page, **dictrem)
сделал с новой функцией

2023-08-06 11:49 UTC, alexeyyS000 commented on app/utils/sql/dal.py
> +            total_pages = len(session.execute(select(self.Config.model).filter_by(**kwargs)).scalars().all()) / limit
сделал

2023-08-06 11:49 UTC, alexeyyS000 commented on app/utils/sql/dal.py
> +            raise ValueError
сделал

2023-08-06 11:50 UTC, alexeyyS000 commented on app/utils/sql/dal.py
> +            total_pages = len(session.execute(select(self.Config.model).filter_by(**kwargs)).scalars().all()) / limit
добавил функцию пагинации прямо в api, возможно эта функция уже не нужна

2023-08-06 11:50 UTC, alexeyyS000 commented on app/api/api.py
> +    one_post = PostDAL(session_maker).get_one_or_none(id=post_id)
тоже пока не разобрался, я так понимаю нужно сделать отдельную сущность которая вернет PostDAL(session_maker) и функции пути будут зависеть от нее ?

2023-08-06 12:23 UTC, swimmwatch commented on app/api/api.py
> +    one_post = PostDAL(session_maker).get_one_or_none(id=post_id)
Да, нужно сделать функцию-фабрику, которая будет возвращать экземпляр `PostDAL(session_maker)`.

2023-08-06 12:53 UTC, swimmwatch requested changes

2023-08-06 12:53 UTC, swimmwatch commented on app/api/api.py
> +        return {"result": result, "prev_page": prev_page, "next_page": next_page, "total_pages": total_pages}
Лучше вынести логику пагинации в репозиторий, чтобы можно было переиспользовать.

2023-08-06 12:53 UTC, swimmwatch commented on app/api/schemas.py
> +class Post(BaseModel):
Лучше переименуй класс `Post` в `BasePost`, чтобы подчеркнуть что это базовый класс (как раз не нужно будет делать `Post as ORMPost`).

2023-08-06 12:53 UTC, swimmwatch commented on app/api/schemas.py
> +class ResponsPostFilter(BaseModel):
Лучше назвать `PostPaginatedResponse`, так как данная схема Pydantic имеет отношение к пагинации, а не к фильтрации.

2023-08-06 12:53 UTC, swimmwatch commented on app/utils/sql/dal.py
> +    def get_session(self):
Для чего нужен данный метод?

2023-08-06 12:53 UTC, swimmwatch commented on docker-compose.yaml
> +    command: uvicorn api.main:app --reload
В продакшене нужно использовать gunicorn, а не uvicorn. Про это можно [прочитать в документации FastAPI](https://fastapi.tiangolo.com/deployment/server-workers/).

2023-08-06 12:53 UTC, swimmwatch commented on docker-compose.yaml
> +    command: uvicorn api.main:app --reload
Также не нужно указывать флаг `--reload`, так как у тебя стоит политика `restart: always`.

2023-08-06 12:53 UTC, swimmwatch commented on app/api/api.py
> +    dictrem = {keys: values for keys, values in criteria_dict.items() if values is not None}
Логика фильтрации реализована в `fastapi-filter`.

2023-08-06 12:53 UTC, swimmwatch commented on app/api/schemas.py
> +        model = ORMPost
Лучше это вынести в отдельный модуль (например, `filters.py`), так как это уже не относится к схемам Pydantic.

2023-08-06 12:53 UTC, swimmwatch commented on app/utils/sql/dal.py
> +            total_pages = ceil(session.query(self.Config.model).filter_by(**kwargs).count() / limit)
1. Давай лучше использовать везде новый синтаксис запросов. Чтобы было единообразие и не использовать легаси функционал.
2. Нужно вычисления проводить на уровне запроса, а не на уровне Python. В [данном комментарии](https://github.com/alexeyyS000/metropoliten/pull/8#discussion_r1283459437) описал, как можно это сделать.

2023-08-07 10:55 UTC, swimmwatch reviewed
Посмотрел новые изменения. Все ок. Можно переходить к написанию тестов.

2023-08-17 18:38 UTC, swimmwatch requested changes

2023-08-17 18:38 UTC, swimmwatch commented on app/api/dependencies.py
> +    return PostDAL(test_sesson_marker)
Сессию нужно определять создавать в фикстуре.

2023-08-17 18:38 UTC, swimmwatch commented on app/db/client.py
> +test_sesson_marker = sessionmaker(bind=create_engine(settings.test_url), expire_on_commit=False)
Сессию для тестов нужно создавать в фикстуре.

2023-08-17 18:38 UTC, swimmwatch commented on app/db/config.py
> +    test_db_name: str = "databasefortest"
У тебя есть переменная, которая задает название базы.

2023-08-17 18:38 UTC, swimmwatch commented on app/db/config.py
> +
Дублирование кода.

2023-08-17 18:38 UTC, swimmwatch commented on app/migrations/env.py
> +sys.path.append("/Users/alex1/Desktop/project/metropoliten/app")
Нужно смотреть на рабочую директорию и на alembic.ini.

2023-08-17 18:38 UTC, swimmwatch commented on app/pyproject.toml
> +psycopg2 = "^2.9.7"
Зачем нужен psycopg2? У тебя на проекте уже используется 3-я версия

2023-08-17 18:38 UTC, swimmwatch commented on app/pyproject.toml
> +pytest = "^7.4.0"
pytest нужно устанавливать как зависимость для разработки. Для запуска приложения она не нужна.

2023-08-17 18:38 UTC, swimmwatch commented on app/tests/conftest.py
> +sys.path.append("/Users/alex1/Desktop/project/metropoliten/app")
Нужно смотреть на рабочую директорию.

2023-08-17 18:38 UTC, swimmwatch commented on app/tests/conftest.py
> +client = TestClient(app)
Тестовый клиент инициализируется в фикстуре.

2023-08-17 18:38 UTC, swimmwatch commented on app/tests/conftest.py
> +    create_database(DatabaseSettings().test_url)
Значение `DatabaseSettings()` можно сохранить в переменную и переиспользовать.

2023-08-17 18:38 UTC, swimmwatch commented on app/tests/conftest.py
> +app.dependency_overrides[get_postdal] = override_get_postdal
Это делается в фикстуре

2023-08-17 18:38 UTC, swimmwatch commented on app/tests/conftest.py
> +    test_object = PostDAL(test_sesson_marker).get_or_create(test_data, id=test_data["id"])
Экземпляр репозитория создается в фикстуре

2023-08-17 18:38 UTC, swimmwatch commented on app/tests/conftest.py
> +    test_object = PostDAL(test_sesson_marker).get_or_create(test_data, id=test_data["id"])
Очень много лишний действий. Тут получается ты создаешь запись и удаляешь. Достаточно определить фикстуру, которая только создает запись. Удалить можно через вызов метода репозитория.

2023-08-17 18:38 UTC, swimmwatch commented on app/tests/test_endpoints.py
> +    assert response.status_code == 200
Нужно проверять не только статус ответа, но и сам ответ. Ну или содержимое БД (например, при удалении).

2023-08-18 21:07 UTC, alexeyyS000 commented on app/api/apifor_test.py
> +    return {"msg": "Hello World"}
убрал

2023-08-18 21:07 UTC, alexeyyS000 commented on app/api/dependencies.py
> +    return PostDAL(test_sesson_marker)
исправил

2023-08-18 21:07 UTC, alexeyyS000 commented on app/db/client.py
> +test_sesson_marker = sessionmaker(bind=create_engine(settings.test_url), expire_on_commit=False)
исправил

2023-08-18 21:07 UTC, alexeyyS000 commented on app/db/config.py
> +    test_db_name: str = "databasefortest"
исправил

2023-08-18 21:07 UTC, alexeyyS000 commented on app/db/config.py
> +
удалил

2023-08-18 21:08 UTC, alexeyyS000 commented on app/tests/conftest.py
> +    create_database(DatabaseSettings().test_url)
исправил

2023-08-18 21:08 UTC, alexeyyS000 commented on app/tests/conftest.py
> +app.dependency_overrides[get_postdal] = override_get_postdal
исправил как мог

2023-08-18 21:08 UTC, alexeyyS000 commented on app/tests/test_endpoints.py
> +    assert response.status_code == 200
исправил как мог

2023-08-19 15:38 UTC, alexeyyS000 commented on app/tests/conftest.py
> +    test_object = PostDAL(test_sesson_marker).get_or_create(test_data, id=test_data["id"])
не совсем понял,  удалить можно не фикстурой ? то есть прямо в test_ функции ?

2024-03-07 09:45 UTC, merged